apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-deployment
  namespace: skills
  labels:
    app: red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      serviceAccountName: red-user
      nodeSelector:
        eks.amazonaws.com/nodegroup: gj2025-eks-app-nodegroup
      containers:
      - name: red
        image: 323974325951.dkr.ecr.ap-northeast-2.amazonaws.com/green:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.5"
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USER
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWD
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_URL
