apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: red-rollout
  namespace: skills
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      serviceAccountName: red-user
      nodeSelector:
        eks.amazonaws.com/nodegroup: gj2025-eks-app-nodegroup
      containers:
      - name: red
        image: 323974325951.dkr.ecr.ap-northeast-2.amazonaws.com/red:20250611092057
        ports:
        - containerPort: 8080
        resources:
            requests:
              cpu: "0.5"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USER
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWD
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_URL
  strategy:
    blueGreen:
      activeService: red-active
      previewService: red-preview
      autoPromotionEnabled: true